// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// radix_str
XPtrRadixStr radix_str(std::vector < std::string > key, std::vector < std::string > value);
RcppExport SEXP triebeard_radix_str(SEXP keySEXP, SEXP valueSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::vector < std::string > >::type key(keySEXP);
    Rcpp::traits::input_parameter< std::vector < std::string > >::type value(valueSEXP);
    __result = Rcpp::wrap(radix_str(key, value));
    return __result;
END_RCPP
}
