# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

radix_str <- function(key, value) {
    .Call('triebeard_radix_str', PACKAGE = 'triebeard', key, value)
}

