# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

radix_create_str <- function(keys, values) {
    .Call('triebeard_radix_create_str', PACKAGE = 'triebeard', keys, values)
}

radix_create_int <- function(keys, values) {
    .Call('triebeard_radix_create_int', PACKAGE = 'triebeard', keys, values)
}

radix_create_double <- function(keys, values) {
    .Call('triebeard_radix_create_double', PACKAGE = 'triebeard', keys, values)
}

radix_create_bool <- function(keys, values) {
    .Call('triebeard_radix_create_bool', PACKAGE = 'triebeard', keys, values)
}

radix_len_str <- function(radix) {
    .Call('triebeard_radix_len_str', PACKAGE = 'triebeard', radix)
}

radix_len_int <- function(radix) {
    .Call('triebeard_radix_len_int', PACKAGE = 'triebeard', radix)
}

radix_len_bool <- function(radix) {
    .Call('triebeard_radix_len_bool', PACKAGE = 'triebeard', radix)
}

radix_len_double <- function(radix) {
    .Call('triebeard_radix_len_double', PACKAGE = 'triebeard', radix)
}

